### ISSUE TITLE
Add support for local git repository folder 

### ISSUE THREAD

**Issue by soguy** [BankkRoll/Repo-to-PDF#4]
My repo is on corporate GitHub so I would like to run Repo-to-PDF on a source folder and not a public URL

**Comment by malpou** [comment]
I'll start looking into adding this as an option later this week.

**Comment by malpou** [comment]
This should be solved in #5 

@BankkRoll

**Comment by BankkRoll** [comment]
Thanks @malpou for solving this so quick, also a very good idea so thanks as well for @soguy for bringing it to our attention. Thanks for using repo2pdf also, the change suggested and committed by malpou had been merged :)
